/* Generated By:JavaCC: Do not edit this line. BackEndVisitor.java Version 5.0 */
public interface BackEndVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTMain node, Object data);
}
/* JavaCC - OriginalChecksum=c0d0d3fb30283aeca31a459bc1e34b25 (do not edit this line) */
