/* Generated By:JavaCC: Do not edit this line. BackEndTreeConstants.java Version 5.0 */
public interface BackEndTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTMAIN = 2;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Main",
  };
}
/* JavaCC - OriginalChecksum=98a2fa16850fcf7782284ad3fd685946 (do not edit this line) */
